# rabbitmq/rabbitmq.conf
loopback_users.guest = false
default_vhost = /
default_user = cbom
default_permissions.configure = .*
default_permissions.read = .*
default_permissions.write = .*

# Memory
vm_memory_high_watermark.relative = 0.6
vm_memory_high_watermark_paging_ratio = 0.5

# Persistence
queue_master_locator = min-masters
durable_queues = true

# Delivery confirmation
consumer_timeout = 3600000

# Logging
log.console = true
log.console.level = info
